version: "3"
services:
    nginx:
        build:
            context: .
        ports:
            - "24555:24555"
        networks:
            - mysite_network
        depends_on:
            - server
            - client

    server:
        build:
            context: ./server
        networks:
            - mysite_network
        environment:
            - DOTENV_FILE=/run/secrets/dotenv
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
            - dotenv
            - postgres_password
        depends_on:
            - postgres
            
        develop:
            watch:
                - action: sync
                  path: ./server
                  target: /app

    client:
        build:
            context: ./client
        networks:
            - mysite_network
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /app
                - action: rebuild
                  path: package.json 


    postgres:
        image: postgres:latest
        networks:
            - mysite_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
            - postgres_password

networks:
    mysite_network:
        driver: bridge

secrets:
    dotenv:
        file: .env
    postgres_password:
        file: postgres_password.txt

volumes:
    postgres_data:
