version: '3'
services:
  server:
    build:
      context: ./src/server
    ports:
      - "127.0.0.1:24551:24551"
    networks:
      - mysite_network
  client:
    build:
      context: ./src/client
    ports:
      - "127.0.0.1:24552:24552"
    networks:
      - mysite_network
  nginx:
    build:
      context: .
    ports:
      - "24555:24555"
    networks:
      - mysite_network


networks:
  mysite_network:
    driver: bridge